### ISSUE TITLE
Add editorconfig file for consistency between editors and contributos

### ISSUE THREAD

**Issue by gabrielperales** [dwyl/style-guide#11]
We can use [editorconfig](http://editorconfig.org/) to have the same indentation through differents editors and contributors. We can add an 'standard' editorconfig file to this repository, and then we can add it to all of the repositories.

**Comment by nelsonic** [comment]
@gabrielperales thanks very much again for opening this issue. 🙏  Great suggestion as always. 👌 
Hope you are well. ☀️ ❤️ 

Borrowing sample `.editorconfig` from: https://gist.github.com/JamesMGreene/f4b01ff4a2f8e6faead1 🔗 
Added via: #31 🚀
