### ISSUE TITLE
CSS | Are `px` better than `em` or `rem` after all?

### ISSUE THREAD

**Issue by iteles** [dwyl/style-guide#16]
I've been seeing an increasing number of articles on how we should all go back to `px` over `em`s or `rem`s. This is certainly worth another look but any insights are much appreciated!

http://benfrain.com/just-use-pixels/
https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/

**Comment by iteles** [comment]
Then there's this hodge-podge of craziness: https://css-tricks.com/rems-ems/

**Comment by nelsonic** [comment]
Thankfully, we can side-step most of this with `Tailwind` sizing. 🌈 
But if not, just use what ever is appropriate to the use case you are solving for. 👌
