### ISSUE TITLE
Is it useful to have a 'Git' portion in the style guide?

### ISSUE THREAD

**Issue by iteles** [dwyl/style-guide#2]
Describing things like:
- Adding issues numbers to every commit to ensure there's always traceability
- Writing a good issue
- Writing a descriptive pull request that speeds up review time and reduces the amount of back and forth between the requestee and the assigned reviewer

Would this be useful in the style guide? Does it belong somewhere else?

I'm loathe to create too many repos of this kind of 'guide' stuff and would rather keep them to a minimum, but we do have to capture this somewhere!

**Comment by nelsonic** [comment]
its _essential_.

**Comment by rjmk** [comment]
Also, repo naming? I tend not to keep a history so long repo names can be a bit of a faff for me, but I see the appeal of descriptive name as well. Some guidance would be good.

**Comment by iteles** [comment]
@rjmk :+1:

**Comment by nelsonic** [comment]
I'm a _fan_ of **_descriptive**_ (_says-what-it-does_) repo names for a couple of reasons namely human find-ability and SEO. We have a few projects with single word names: **time**, **tudo**, **esta** and **arana** which are deliberately simple for eventual "branding". But the "_naming convention_" we have used is not _explicit_, we have simply followed the "_is-the-name-available-on-npm_" approach where the project will be a `module` (on NPM) and "_explains-what-it-does_" for everything else.

**Comment by iteles** [comment]
Adds images for style guide.

<img width="723" alt="paired-commit-message" src="https://cloud.githubusercontent.com/assets/4185328/9212496/3adc19c2-4081-11e5-956c-8655c1f37946.png">

<img width="704" alt="commit-message-referenced-from-issue" src="https://cloud.githubusercontent.com/assets/4185328/9212670/dda6840c-4082-11e5-8e58-c4077f5ab089.png">

<img width="695" alt="emojis-in-commit-messages" src="https://cloud.githubusercontent.com/assets/4185328/9212573/14112b74-4082-11e5-822e-bc66250c5712.png">

**Comment by iteles** [comment]
<img width="1487" alt="add-comment-inline-in-pr" src="https://cloud.githubusercontent.com/assets/4185328/9238016/04f9801c-4147-11e5-9a4e-494af82ea141.png">

**Comment by iteles** [comment]
<img width="947" alt="add-comment-inline-in-pr" src="https://cloud.githubusercontent.com/assets/4185328/9238546/0d40fb66-414b-11e5-9a24-23d9e6ed0bc4.png">

<img width="940" alt="add-comment-inline-in-pr-comment-box" src="https://cloud.githubusercontent.com/assets/4185328/9238544/0d293b20-414b-11e5-8604-15ba4f229525.png">

**Comment by iteles** [comment]
<img width="288" alt="history-tab-on-git-documents" src="https://cloud.githubusercontent.com/assets/4185328/9290455/55d5dc6e-438c-11e5-851d-71127213f565.png">

<img width="274" alt="blame-tab-on-git-documents" src="https://cloud.githubusercontent.com/assets/4185328/9290470/e46c2578-438c-11e5-95a7-19dfbcf82b00.png">
