### ISSUE TITLE
Git Commit Messages

### ISSUE THREAD

**Issue by nelsonic** [dwyl/style-guide#21]
## Tips for Writing _Useful_ Git Commit Messages
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages
- https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

> Please add other tips! and #discuss!

**Comment by iteles** [comment]
I've already added mine here: https://github.com/dwyl/style-guide#commits 😉

**Comment by nelsonic** [comment]
Yeah, but for _some_ reason I keep seeing _useless_ or _identical_ (_repeated_) commit messages in projects so I thought I would re-open the issue...

**Comment by nelsonic** [comment]
I've added this to the `README.md` ✅
