### ISSUE TITLE
Single quotes or double quotes?

### ISSUE THREAD

**Issue by tsop14** [dwyl/style-guide#5]
Double quotes "" for html
Single quotes '' for everything else

???

![screen shot 2015-08-12 at 11 16 50](https://cloud.githubusercontent.com/assets/8484757/9221636/adb1838a-40e3-11e5-83d0-afba6f30a2db.png)

**Comment by nelsonic** [comment]
I _prefer_ single quotes _all-the-things_ ...
However they are not valid JSON:

![json-lint-single-quotes](https://cloud.githubusercontent.com/assets/194400/9222073/bf18f4fc-40e6-11e5-8fc5-61087fc1c298.png)

**Comment by nelsonic** [comment]
Rule of thumb:

> use single-quotes everywhere. except when constructing a string which includes styles or properties which are themselves denoted by single-quotes:
> e.g: `var str = "<a class='big' href='/mylink'>click me</a>"`;
> And when _manually_ creating a **JSON** object/file

**Comment by tsop14** [comment]
@dwyl/summer
